### ISSUE TITLE
Backward compatibility with WebGL1

### ISSUE THREAD

**Issue by bhousel** [rapideditor/pixi-texture-allocator#1]
There is some code here that seems to be WebGL2 only, and it would be nice to be backward compatible with WebGL1 for older devices.

in `AtlasResource.uploadItem`:
https://github.com/rapideditor/pixi-texture-allocator/blob/6210000cd7bc8bbc177216c2e95ac902fe26b757/src/AtlasResource.ts#L150-L160

Causes
```
TypeError: Failed to execute 'texSubImage2D' on 'WebGLRenderingContext': parameter 9 is not of type 'ArrayBufferView'.
    at AtlasResource.uploadItem (AtlasResource.ts:150:12)
    at AtlasResource.upload (AtlasResource.ts:112:18)
    at TextureSystem.updateTexture (TextureSystem.ts:326:31)
    at TextureSystem.bind (TextureSystem.ts:169:22)
    ...
 ```

**Comment by bhousel** [comment]
related to 
https://github.com/facebook/Rapid/issues/493
https://github.com/facebook/Rapid/issues/568
https://github.com/facebook/Rapid/issues/478#issuecomment-1139841965
